services:
  legacy-api:
    build:
      context: ./legacy-api
    container_name: legacy-api
    restart: always
    ports:
      - "4040:4040"

  new-recruitment-api:
    build:
      context: ./new-recruitment-api
    container_name: new-recruitment-api
    restart: always
    depends_on:
      - legacy-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/data/recruitment.db"
      LEGACY_API_URL: "http://legacy-api:4040"
      LEGACY_API_KEY: "0194ec39-4437-7c7f-b720-7cd7b2c8d7f4"
      PORT: "3000"
    volumes:
      - new-api-data:/data

volumes:
  new-api-data: